= BLisp: Statically Typed Lisp Like Language
Yuuki Takano <ytakano@wide.ad.jp>
v0.1, 2021-02
:doctype: article
:toc:
:encoding: utf-8
:stem: latexmath
:source-highlighter: pygments


BLisp is a statically typed Lisp like programming language which adopts effect system for no_std environments.
BLisp supports higher order RPC like higher order functions of functional programing languages.

This repository provides only a library crate.
Please see https://github.com/ytakano/blisp-repl[blisp-repl] to use BLisp,
and https://github.com/ytakano/baremetalisp[baremetalisp] which is a toy OS.

== Features

* Algebraic data type
* Generics
* Hindley–Milner based type inference
* Effect system to separate side effects from pure functions
* Big integer
* Supporting no_std environments

== Values

.values
[source, lisp]
----
144       ; integer value
true      ; boolean value
false     ; boolean value
[true 10] ; tuple
[]        ; empty tuple
'(1 2 3)  ; list
'()       ; empty list, Nil
----

== Basic Types

.types
[source, lisp]
----
Int        ; signed integer
Bool       ; boolean
'(Int)     ; list of Int
[Int Bool] ; tuple of Int and Bool
(Pure (-> (Int Int) Bool)) ; Pure function, which takes 2 integers and return boolean value
(IO (-> (Int) [])) ; IO function, which takes an integer and return []
----

Pure and IO are function effects.
In IO functions, both Pure and IO functions can be called.
However, in Pure functions, calling only Pure functions is permitted.

== Function Definition

Functions can be defined by defun or export.
"defun" defines a local function which cannot be called from Rust's eval function.

Suppose following 2 functions.

.defun
[source, lisp]
----
(defun double (x)         ; function name is "double" and "x" is an argument
    (Pure (-> (Int) Int)) ; function Type
    (* 2 x))              ; function body
----

.export
[source, lisp]
----
(export quad (x)          ; function name is "quad" and "x" is an argument
    (Pure (-> (Int) Int)) ; function Type
    (double (double x)))  ; function body
----

double cannot be called from Rust's eval, but can be called from internally defined functions.
qued can be called from Rust's eval, and it calls double internally.

This is the code what actually do in Rust.

.Rust's eval
[source, rust]
----
use blisp;

fn eval(e: &str, ctx: &blisp::semantics::Context) {
    // evaluate expressions
    let exprs = match blisp::eval(e, ctx) {
        Ok(es) => es,
        Err(err) => {
            println!("error:{}:{}: {}", err.pos.line, err.pos.column, err.msg);
            return;
        }
    };

    for r in exprs {
        match r {
            Ok(msg) => {
                println!("{}", msg);
            }
            Err(msg) => {
                println!("error: {}", msg);
            }
        }
    }
}

fn main() {
    // internal code
    let code = "
(defun double (x)         ; function name is double and x is an argument
    (Pure (-> (Int) Int)) ; function Type
    (* 2 x))              ; function body

(export quad (x)          ; function name is quad and x is an argument
    (Pure (-> (Int) Int)) ; function Type
    (double (double x)))  ; function body
";
    let exprs = blisp::init(code).unwrap();
    let ctx = blisp::typing(&exprs).unwrap();

    let e = "(double 10) ; error";
    eval(e, &ctx);

    let e = "(quad 10) ; OK";
    eval(e, &ctx);
}
----

This code output as follows.

 error:0:1: Typing Error: double is not defined
 40

== Arithmetic Operations

.basic
[source, lisp]
----
; (Pure (-> (Int Int) Int))
(+ 10 20)
(- 30 40)
(* 6 100)
(/ 100 2)
(% 10 3)
----

.comparison
[source, lisp]
----
; (Pure (-> (Int Int) Bool))
(= 4 4)
(< 6 7)
(> 6 7)
(<= 30 40)
(>= 30 40)
----

== Boolean Operations

.logical
[source, lisp]
----
; (Pure (-> (Bool Bool) Bool))
(and true false)
(or true false)
(xor true false)
----

.negation
[source, lisp]
----
; (Pure (-> (Bool) Bool))
(not true)
----